//
//  CurrencyPresenter.swift
//  FiatMoneyCoin
//
//  Created tambanco 🥳 on 05.07.2022.
//
//  Template generated by Tambanco
//

import Foundation
import UIKit

// MARK: Output protocol
protocol CurrencyViewProtocol: AnyObject {
    func setTotalValue(value: String, currencyList: [String])
    func present(viewControllerToPresent: UIViewController)
}

// MARK: Input protocol
protocol CurrencyPresenterProtocol: AnyObject {
    init(router: RouterProtocol, view: CurrencyViewProtocol, model:  CurrencyModel)
    func getCurrencyList()
    func showFiatView(amount: String, symbol: String)
}

class CurrencyPresenter: CurrencyPresenterProtocol {
    
    weak var view: CurrencyViewProtocol?
    var router: RouterProtocol?
    var model: CurrencyModel
    
    func showFiatView(amount: String, symbol: String) {
//        let fiatVC = ModuleBuilder.createFiatModule(amount: amount, currencySymbol: symbol)
        let fiatVC = FiatViewController()
        fiatVC.modalPresentationStyle = .fullScreen
        view?.present(viewControllerToPresent: fiatVC)
    }
    
    func getCurrencyList() {
//        view?.setTotalValue(value: String(model.amount), currencyList: model.symbols)
    }
    
    required init(router: RouterProtocol, view: CurrencyViewProtocol, model: CurrencyModel) {
        self.router = router
        self.view = view
        self.model = model
    }
}
