//
//  CurrencyPresenter.swift
//  FiatMoneyCoin
//
//  Created tambanco 🥳 on 05.07.2022.
//
//  Template generated by Tambanco
//

import Foundation
import UIKit
import CoreData

// MARK: Output protocol
protocol CurrencyViewProtocol: AnyObject {
    func success()
    func failure(error: Error)
}

// MARK: Input protocol
protocol CurrencyPresenterProtocol: AnyObject {
    var newValueToSave: String? { get set }
    var newSymbolToSave: String? { get set }
    var symbols: [String]? { get set }
    var baseCurrency: String { get }
    var convertedCurrency: String? { get set }
    var storageService: StorageService? { get set }
    func saveToCoreData()
    func cancelAdding()
    init(router: RouterProtocol, view: CurrencyViewProtocol, networkService: NetworkServiceProtocol)
}

class CurrencyPresenter: CurrencyPresenterProtocol {
    var convertedCurrency: String?
    var baseCurrency: String = "RUB"
    var newValueToSave: String?
    var newSymbolToSave: String?
    var storageService: StorageService? = StorageService()
    var symbols: [String]? = []
    
    weak var view: CurrencyViewProtocol?
    var router: RouterProtocol?
    var networkService: NetworkServiceProtocol?
    
    func saveToCoreData() {
        currencyConverter(amount: newValueToSave, symbol: newSymbolToSave)
        storageService?.saveNewValue(newValue: newValueToSave, newSymbol: newSymbolToSave)
        router?.popToRoot()
    }
    
    func currencyConverter(amount: String?, symbol: String?) {
        guard symbol != nil else { return }
        let symbolToConvert = symbol!
        let currencyCode = String(symbolToConvert.prefix(3))
        networkService?.convertTwoCurrensies(from: currencyCode, to: baseCurrency, amount: amount ?? "", completion: { [weak self] result in
            guard let self = self else { return }
            DispatchQueue.main.async {
                switch result {
                case .success(let convertedValue):
                    self.convertedCurrency = convertedValue
                    self.storageService?.saveCurrency(totalValue: self.newValueToSave,
                                                     convertedValue: self.convertedCurrency,
                                                     currencySymbol: self.newSymbolToSave)
                case .failure(let error):
                    print(error.localizedDescription)
                }
            }
        })
    }
    
    func cancelAdding() {
        router?.popToRoot()
    }
    
    required init(router: RouterProtocol, view: CurrencyViewProtocol, networkService: NetworkServiceProtocol) {
        self.router = router
        self.view = view
        self.networkService = networkService
        
        getSymbols()
    }
    
    func getSymbols() {
        networkService?.getCurrencyList(completion: { [weak self] result in
            guard let self = self else { return }
            DispatchQueue.main.async {
                switch result {
                case .success(let symbols):
                    self.symbols = symbols
                    self.view?.success()
                case .failure(let error):
                    self.view?.failure(error: error)
                }
            }
        })
    }
}
