//
//  CurrencyPresenter.swift
//  FiatMoneyCoin
//
//  Created tambanco 🥳 on 05.07.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol CurrencyViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol CurrencyPresenterProtocol: AnyObject {
    init(view: CurrencyViewProtocol, model:  CurrencyModel)

}

class CurrencyPresenter: CurrencyPresenterProtocol {

    weak var view: CurrencyViewProtocol?
    var model: CurrencyModel
    
    // Enter buisness logic here
    
    required init(view: CurrencyViewProtocol, model: CurrencyModel) {
        self.view = view
        self.model = model
    }
}
