//
//  FiatPresenter.swift
//  FiatMoneyCoin
//
//  Created tambanco 🥳 on 28.06.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol FiatViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol FiatPresenterProtocol: AnyObject {
    func getLatestRate()
    init(view: FiatViewProtocol, model:  FiatModel)

}

class FiatPresenter: FiatPresenterProtocol {
    weak var view: FiatViewProtocol?
    var model: FiatModel
    
    func getLatestRate() {
        NetworkManager.getLatest(base: "RUB", symbols: "USD")
    }
    
    
    // Enter buisness logic here
    
    required init(view: FiatViewProtocol, model: FiatModel) {
        self.view = view
        self.model = model
    }
}
