//
//  FiatModel.swift
//  FiatMoneyCoin
//
//  Created tambanco 🥳 on 28.06.2022.
//
//  Template generated by Tambanco
//

import Foundation

struct FiatRawModel: Codable {
    let base, date: String
    let rates: Rates
    let success: Bool
    let timestamp: Int
}

struct Rates: Codable {
    let usd: Double

    enum CodingKeys: String, CodingKey {
        case usd = "USD"
    }
}
