//
//  CurrencyViewController.swift
//  FiatMoneyCoin
//
//  Created tambanco 🥳 on 05.07.2022.
//
//  Template generated by Tambanco
//

import UIKit

class CurrencyViewController: UIViewController {

	var presenter: CurrencyPresenterProtocol!
    
    var totalValue: String = ""
    var currencyList: [String] = []

    @IBOutlet weak var addCurrencyTF: UITextField!
    @IBOutlet weak var currencyPV: UIPickerView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.getCurrencyList()
        setupCurrencyView()
        setupPickerView()
    }
    
    func  setupCurrencyView() {
    }
    
    func setupPickerView() {
        currencyPV.delegate = self
        currencyPV.dataSource = self
        
    }
    
    @IBAction func cancelButton(_ sender: UIButton) {
        self.dismiss(animated: true)
    }
    
    @IBAction func addButton(_ sender: UIButton) {
    }
}

// MARK: - Binding
extension CurrencyViewController: CurrencyViewProtocol {
    func setTotalValue(value: String, currencyList: [String]) {
        self.totalValue = value
        self.currencyList = currencyList
    }
}

extension CurrencyViewController: UIPickerViewDelegate, UIPickerViewDataSource {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return currencyList.count
    }
    
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        return currencyList[row]
    }
}
